---
# jenkins nodes related tasks file for jenkins_server

- name: 'Create nodes folder'
  become: yes
  file:
    path=/var/lib/jenkins/nodes
    state=directory
    owner=jenkins
    group=jenkins

- name: 'Create a folder for each node'
  become: yes
  file:
    path="/var/lib/jenkins/nodes/{{ item.name }}"
    state=directory
    owner=jenkins
    group=jenkins
  with_items: "{{ nodes_info }}"

- name: 'Configure each node'
  become: yes
  template:
    src=node.xml.j2
    dest="/var/lib/jenkins/nodes/{{ item }}/config.xml"
    owner=jenkins
    group=jenkins
  with_items: "{{ nodes_info }}"
  notify:
    - 'restart jenkins'
